config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # home page for the weather app.
  root "weather#home"
  
  get "weather_for_zip" => "weather#weather_for_zip"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/zip_code.rb
class ZipCode < ApplicationRecord
  validates :zip_code, uniqueness: true, presence: true, format: { with: /\A\d{5}\z/, message: 'must be exactly 5 digits' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def home
    # root path.
  end
  
  def weather_for_zip
    @zip_code = ZipCode.find_or_initialize_by(weather_params)
    
    # TODO: store this object in Redis in the future, ex:
    #   @weather_object = with_cache("weather_for_#{@zip_code}", 30.minutes) { WeatherForZipCodeService.call(@zip_code) }
    @weather_object = WeatherForZipCodeService.call(@zip_code)
    
    render :home
  end
  
  private
  
  def weather_params
    params.permit(:zip_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
  
  # input: a zip code object
  # output: how many minutes ago, in words, the weather forecast was retrieved at.
  def retrieved_at_minutes_ago(retrieved_at)
    time_ago_in_words(retrieved_at, include_seconds: true)
  end

  # input: a zip code object
  # output: how many minutes, in words, until the weather forecast gets refreshed.
  def will_refresh_at_in_minutes(retrieved_at)
    distance_of_time_in_words(DateTime.current, retrieved_at + 30.minutes, include_seconds: true)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherLookupTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/home.html.erb
<div class="center">
  <% if @weather_object.blank? %>
    <div id="get-started-instructions">
      Please input a zip code to get started!
    </div>
  <% elsif @weather_object[:error].present? %>
    <p id="error-text" class="red"><%= @weather_object[:error] %></p>
  <% else %>
    <!-- INFO ABOUT WHEN THE WEATHER WAS FETCHED -->
    <div id="weather-fetched-at-information">
      <% if @weather_object[:pulled_from_cache] %>
        <div id="weather-pulled-from-cache-info" class="orange">
          <p>
            The following weather was retrieved <strong><%= retrieved_at_minutes_ago(@zip_code.weather_retrieved_at) %> ago.</strong>
            <br>
            It will refresh in <strong><%= will_refresh_at_in_minutes(@zip_code.weather_retrieved_at) %>.</strong>
          </p>.
        </div>
      <% else %>
        <p id="up-to-date-weather-info" class="limegreen">
          This is the most up-to-date weather forecast!
        </p>
      <% end %>
    </div>
    
    <!-- ACTUAL WEATHER INFORMATION -->
    <div id="weather-information">
      <% weather = @weather_object[:weather] %>
      <% location_info = weather['location'] %>
      <% current_weather = weather['current'] %>
      
      <div id="location">
        Location: <strong><%= location_info&.[]('name') %>, <%= location_info&.[]('region') %> (<%= @zip_code&.zip_code %>)</strong>
      </div>
      <br>
      <div id="current-weather">
        Current Weather: <strong><%= current_weather.dig('condition', 'text') || 'not available!' %></strong>
      </div>
      <br>
      <!-- `&#8457` => fahrenheit symbol. `&#8451;` => celsius symbol. -->
      <div id="current-temperature">
        Temperature: <strong><%= current_weather['temp_f'] %> &#8457; (<%= current_weather['temp_c'] %> &#8451;)</strong>
      </div>
      <br>
      <div id="feels-like-temperature">
        Feels like: <strong><%= current_weather['feelslike_f'] %> &#8457; (<%= current_weather['feelslike_c'] %> &#8451;)</strong>
      </div>
      <br>
      <div id="wind-gusts">
        Wind Gusts: <strong><%= current_weather['gust_mph'] %> mph (<%= current_weather['gust_kph'] %> kph)</strong>
      </div>
    </div>
  <% end %>
</div>

<br>
<br>

<!-- FORM TO INPUT A ZIP CODE -->
<div class="center">
  <%= form_with(url: weather_for_zip_path, method: :get) do |form| %>
    <div>
      <%= form.label :zip_code, 'Zip Code' %>
    </div>
    <div>
      <%= form.text_field :zip_code, value: @zip_code&.zip_code %>
    </div>
    <br>
    <div>
      <%= form.submit 'Submit' %>
    </div>
  <% end %>
</div>